// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCore.DataAccess.Data;

#nullable disable

namespace TechCore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240503165007_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCoreWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Cooling"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Power Supply"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Case"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Peripherals"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
